<a href="https://colab.research.google.com/github/19PA1A0201/AI-Lab/blob/master/Experiment_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1) NumPy 
* Different ways to create NumPy arrays 
* Add, remove, modify elements in an array. 
* Arithmetic operations on NumPy array 
* Slicing and iterating of NumPy arrays 
* Matrix operations on NumPy arrays 


## 1)Different ways to create a Numpy arrays.

In [ ]:
# Create a numpy array
import numpy as np
x = np.array([1,2,3])
print(x)

[1 2 3]


In [ ]:
#  Create a 2d array
y = np.array([[4,5,6],[7,8,9]])
print(y)

[[4 5 6]
 [7 8 9]]


In [ ]:
# Craete a numpy array from 10 to 30 with intervel of 5
import numpy as np
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

## 2) Add, remove, modify elements in an array.

### 2.1) Adding an element to an array

In [ ]:
b = np.append(x,[6,4,2])
print(b)

[1 2 3 6 4 2]


### 2.2) Remove element/s from an array

In [ ]:
print("The elements in X before deleting",x)
newarray = np.delete(x,2) # Element at index 2 is removed.
print("The elements in X after deleting",newarray) 

The elements in X before deleting [1 2 3]
The elements in X after deleting [1 2]


### 2.3) Modify elements in the array

In [ ]:
b = np.array([6,4,1,3,5,9])
b[b<4] = -1 # Elements less than 4 are replaced with "-1"
print(b)

[ 6  4 -1 -1  5  9]


## 3) Arithmetic operations on NumPy array

In [ ]:
# Let's create two arrays
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print("The elements in a are",a)
print("The elements in b are",b)

print("Result after Addition",a+b)
print("Result after substraction",a-b)
print("Result after multiplication",a*b)
print("Result after division",a/b) # Even python is able to handle divided by 0 error by just a warning

print("Result after increasing the number to the power of 4",b**4) # Scalar multiplication(power)

print("Result after applying sin and multiplying with 10",10*np.sin(a)) # trignometric functions are available in numpy package

a[0] +=10 # This is equalient to a[0]=a[0]+10
print("Result after adding first element with 10",a)

print(np.dot(a,b)) # Matrix multiplication

The elements in a are [20 30 40 50]
The elements in b are [0 1 2 3]
Result after Addition [20 31 42 53]
Result after substraction [20 29 38 47]
Result after multiplication [  0  30  80 150]
Result after division [        inf 30.         20.         16.66666667]
Result after increasing the number to the power of 4 [ 0  1 16 81]
Result after applying sin and multiplying with 10 [ 9.12945251 -9.88031624  7.4511316  -2.62374854]
Result after adding first element with 10 [30 30 40 50]
260


<ipython-input-27-fb6e41aaac66>:10: RuntimeWarning: divide by zero encountered in true_divide
  print("Result after division",a/b) # Even python is able to handle divided by 0 error by just a warning


## 4) Slicing and iterating of NumPy arrays

### 4.1) Slicing 1-D array

In [ ]:
# Slicing a 1-D array

a=np.arange(10)**3
print("Let's consider the elements",a)

print("The output of a[2] is", a[2]) # Prints the element at index 2. i.e 3rd element of the array a
print("The output of a[2:4] is",a[2:4]) # Prints the element from index 2 to index 3. Note that a[2:4] means elements from 2 upto 4 (But not including 4).
print("The output of a[2:3] is",a[2:3]) # Note that this returns an array with 1 element. But a[2] returns a scalar element

print("The output of a[-1] is",a[-1]) # prints last element
print("The output of a[-2] is",a[-2]) # prints last but element
print("The output of a[-5:-2] is",a[-5:-2]) # prints 5th ,6th and 7th element. i.e -5,-4,-3

Let's consider the elements [  0   1   8  27  64 125 216 343 512 729]
The output of a[2] is 8
The output of a[2:4] is [ 8 27]
The output of a[2:3] is [8]
The output of a[-1] is 729
The output of a[-2] is 512
The output of a[-5:-2] is [125 216 343]


### 4.1) Slicing 2-D array

In [ ]:
# Slicing a 2-D array

a=np.arange(12).reshape(4,3)**2 # Create an array "a" with square of numbers from 0 to 11.
print("The output of a[2] is",a)

print("The output of a[1:3] is",a[1:3]) # Prints second and third rows
print("The output of a[1:3,1:2] is",a[1:3,1:2]) # from second and third rows, print second column
print("The output of a[2,] is",a[2,])# print 3rd row
print("The output of a[:3,] is",a[:3,])# print 1st, 2nd and 3rd row

print("The output of a[-1,] is",a[-1,]) # Prints last row
print("The output of a[-1,-1] is",a[-1,-1]) # print element at last row and last column


The output of a[2] is [[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]
The output of a[1:3] is [[ 9 16 25]
 [36 49 64]]
The output of a[1:3,1:2] is [[16]
 [49]]
The output of a[2,] is [36 49 64]
The output of a[:3,] is [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
The output of a[-1,] is [ 81 100 121]
The output of a[-1,-1] is 121


### 4.3) Iterating
Iterating over multidimensional arrays is done with respect to the first axis.

In [ ]:
a=np.arange(12).reshape(4,3)**2 # Create an array "a" with square of numbers from 0 to 11.
print("Let's consider an array",a)
print("\n")
for i in a:
    print(i)

Let's consider an array [[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]


[0 1 4]
[ 9 16 25]
[36 49 64]
[ 81 100 121]


## 5)Matrix operations on NumPy arrays

In [ ]:
a=np.floor(10*np.random.random((3,4))) # Create a rondom 3*4 matrix.
print("Let's consider a 1-D array\n",a)
print("After reshaping to 2 by 6 matrix\n",a.reshape(2,6))
print("To Flatten the array\n",a.ravel())
print("To transpose the array\n",a.T)

Let's consider a 1-D array
 [[6. 2. 4. 5.]
 [1. 0. 6. 4.]
 [1. 7. 4. 8.]]
After reshaping to 2 by 6 matrix
 [[6. 2. 4. 5. 1. 0.]
 [6. 4. 1. 7. 4. 8.]]
To Flatten the array
 [6. 2. 4. 5. 1. 0. 6. 4. 1. 7. 4. 8.]
To transpose the array
 [[6. 1. 1.]
 [2. 0. 7.]
 [4. 6. 4.]
 [5. 4. 8.]]
